name: Lint

on:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
